========================================
Total Params: 71891291
Trainable Params: 71891291
Non-trainable Params: 0
========================================
LOG FORMAT | segmentation_LOSS mIoU pixAcc | depth_LOSS abs_err rel_err | normal_LOSS mean median <11.25 <22.5 <30 | TIME
Epoch 0/199
self_multiinpout False
753
  0%|                                                                                                                                     | 0/753 [00:00<?, ?it/s]
{'segmentation': [0.00656227208673954, 0.07414713501930237], 'depth': [0.70698082447052, 1.491173267364502], 'normal': [93.37166, 91.82988, 0.0033268229166666667, 0.016206597222222223, 0.03268229166666667]}
{'train_seg': <utils.SegLoss object at 0x7efdc57a4670>, 'train_dep': <utils.DepthLoss object at 0x7efdc57a4dc0>, 'train_nor': <utils.NormalLoss object at 0x7efdc57a4bb0>}
  0%|                                                                                                                                     | 0/753 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "examples/warehouseSIM/train_warehouseSIM.py", line 126, in <module>
    main(params)
  File "examples/warehouseSIM/train_warehouseSIM.py", line 118, in main
    NYUmodel.train(nyuv2_train_loader, nyuv2_test_loader, 200)
  File "/home/dim/mdpi_robotics/LibMTL/LibMTL/trainer.py", line 249, in train
    self.wandb_run.log({"train_losses": train_loss_dict, "train_metrics": train_metrics_dict},step=epoch)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 370, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 333, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1714, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1496, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1366, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 579, in publish_partial_history
    item.value_json = json_dumps_safer_history(v)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/util.py", line 969, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/wandb/util.py", line 934, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SegLoss is not JSON serializable