========================================
Total Params: 71891291
Trainable Params: 71891291
Non-trainable Params: 0
========================================
LOG FORMAT | segmentation_LOSS mIoU pixAcc | depth_LOSS abs_err rel_err | normal_LOSS mean median <11.25 <22.5 <30 | TIME
Epoch 0/199
self_multiinpout False
753
  0%|                                                      | 0/753 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/dim/mdpi_robotics/LibMTL/LibMTL/trainer.py", line 138, in _process_data
    data, label = loader[1].next()
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dim/mdpi_robotics/LibMTL/mine/create_dataset2.py", line 170, in __getitem__
    image = transforms.Resize(self.resulution)(image)
AttributeError: 'warehouseSIM' object has no attribute 'resulution'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "examples/warehouseSIM/train_warehouseSIM.py", line 128, in <module>
    main(params)
  File "examples/warehouseSIM/train_warehouseSIM.py", line 120, in main
    NYUmodel.train(nyuv2_train_loader, nyuv2_test_loader, 200)
  File "/home/dim/mdpi_robotics/LibMTL/LibMTL/trainer.py", line 217, in train
    train_inputs, train_gts = self._process_data(train_loader)
  File "/home/dim/mdpi_robotics/LibMTL/LibMTL/trainer.py", line 141, in _process_data
    data, label = loader[1].next()
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dim/anaconda3/envs/libmtl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dim/mdpi_robotics/LibMTL/mine/create_dataset2.py", line 170, in __getitem__
    image = transforms.Resize(self.resulution)(image)
AttributeError: 'warehouseSIM' object has no attribute 'resulution'